import unittest
from .. import *
class FleetCase(unittest.TestCase):
    def test_start(self):
        ship_1 = ship.Ship('location'=location.Location(), 'cargo'=cargo.Cargo('titanium'=100, 'cargo_max'=200))
        ship_2 = ship.Ship('location'=location.Location(), 'cargo'=cargo.Cargo('people'=100, 'cargo_max'=200))
        fleet_one = fleet.Fleet('ships'=[ship_1, ship_2])
        ship_3 = ship.Ship('location'=location.Location(), 'cargo'=cargo.Cargo('silicon'=100, 'cargo_max'=100))
        ship_4 = ship.Ship('location'=location.Location(), 'cargo'=cargo.Cargo('lithium'=100, 'cargo_max'=300))
        fleet_two = fleet.Fleet('ships'=[ship_4, ship_3], 'waypoints'=[waypoint.Waypoint('actions'=['merge'], 'recipiants'={'merge':fleet_one}, 'location'=location.LocationReferance(fleet_one))])
        self.assertEqual(ship_1.cargo.titanium, 50)
        self.assertEqual(ship_1.cargo.people, 50)
        self.assertEqual(ship_2.cargo.titanium, 50)
        self.assertEqual(ship_2.cargo.people, 50)
        self.assertEqual(ship_3.cargo.lithium, 25)
        self.assertEqual(ship_3.cargo.silicon, 25)
        self.assertEqual(ship_4.cargo.lithium, 75)
        self.assertEqual(ship_4.cargo.silicon, 75)
    def test_merge(self):
        fleet_two.execute('merge')
        self.assertEqual(ship_1.cargo.titanium, 25)
        self.assertEqual(ship_1.cargo.people, 25)
        self.assertEqual(ship_1.cargo.lithium, 25)
        self.assertEqual(ship_1.cargo.silicon, 25)
        self.assertEqual(ship_2.cargo.titanium, 25)
        self.assertEqual(ship_2.cargo.people, 25)
        self.assertEqual(ship_2.cargo.lithium, 25)
        self.assertEqual(ship_2.cargo.silicon, 25)
        self.assertEqual(ship_3.cargo.titanium, 12)
        self.assertEqual(ship_3.cargo.people, 13)
        self.assertEqual(ship_3.cargo.lithium, 12)
        self.assertEqual(ship_3.cargo.silicon, 13)
        self.assertEqual(ship_4.cargo.titanium, 38)
        self.assertEqual(ship_4.cargo.people, 37)
        self.assertEqual(ship_4.cargo.lithium, 38)
        self.assertEqual(ship_4.cargo.silicon, 37)
